CREATE TABLE STUDENT(
   STUDENT_ID INT IDENTITY(1000001,1) NOT NULL PRIMARY KEY,
   NAME VARCHAR(255) NOT NULL UNIQUE,
   BIRTHDATE DATE,
   GENDER VARCHAR(20) CHECK (GENDER IN ('Male', 'Female'))
);
GO
CREATE TABLE TEACHER(
   TEACHER_ID INT IDENTITY(1000001,1) NOT NULL PRIMARY KEY,
   NAME VARCHAR(255),
   CREATED_DATE DATETIME,
   UPDATE_DATE datetime DEFAULT (getdate())
);
GO
CREATE TABLE COURSE(
   COURSE_ID INT IDENTITY(1000001,1) NOT NULL PRIMARY KEY,
   NAME VARCHAR(255),
   TEACHER_ID INT,
   CREATED_DATE DATETIME,
   UPDATE_DATE datetime DEFAULT (getdate()),
   CONSTRAINT FK_COURSE_TEACHER FOREIGN KEY (TEACHER_ID) REFERENCES TEACHER(TEACHER_ID)
);
GO
CREATE TABLE SCORE(
   SCORE_ID INT IDENTITY(1000001,1) NOT NULL PRIMARY KEY,
   STUDENT_ID INT, 
   COURSE_ID INT,
   SCORE INT,
   CREATED_DATE datetime DEFAULT (getdate()),
   CONSTRAINT FK_SCORE_COURSE FOREIGN KEY (COURSE_ID) REFERENCES COURSE(COURSE_ID),
   CONSTRAINT FK_SCORE_STUDENT FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT(STUDENT_ID)
);
GO